name: Rubin Del Monte
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#ff9797'
    - '#ec6a6c'
    - '#62130f'
    - '#a13938'
  brandStrength: 0.6781632520724088
  lightness: 0.3139500205870718
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
