name: Rubin Del Monte
favicon: null
layout_spectrum: 0.75032
typography_spectrum: 0.75244
title: Gems from the mountain of music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#ff9797'
    - '#ec6a6c'
    - '#62130f'
    - '#a13938'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
